{
 "title": "telnet-server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{pod=~\"telnet-server-.*\",container!=\"\", container!=\"POD\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"telnet-server-.*\"}[5m] ) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Total Connections",
   "type": "graph",
   "description": "The total connections of telnet-server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(telnet_server_connection_total{job=\"kubernetes-pods\"}) ",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "telnet_server_active_connections{job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total Connection Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(telnet_server_connection_errors_total)"
    }
   ]
  },
  {
   "title": "Unknown Commands Total",
   "type": "stat",
   "description": "Total Unknown Commands",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(telnet_server_unknown_commands_total{job=\"kubernetes-pods\"})"
    }
   ]
  }
 ]
}